name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2233
          script: |
            cd /github/chery-web
            sudo git pull
            sudo git status
            
            sudo rm -rf dist
            source ~/.bashrc
            npm i
            npm run build
            pm2 restart all